import PositiveYaxisAnimate from "@/components/animation/PositiveYaxisAnimate";
import Chat from "@/components/chat/Chat";
import NProgressBar from "@/components/NProgressBar";
import Footer from "@/sections/Footer";
import Navbar from "@/sections/Navbar";
import TopBanner from "@/sections/TopBanner";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const poppins_init = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Care2 Training Consultancy",
  description: "Generated by Abdullah Al Rafee",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins_init.className} overflow-x-hidden`}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <NProgressBar />
        <PositiveYaxisAnimate>
          <TopBanner />
          <Navbar />
        </PositiveYaxisAnimate>
        {children}
        <Chat />
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
